export const INCREASE_COUNTER="INCREASE_COUNTER" /*Arttırma */
export const DECREASE_COUNTER="DECREASE_COUNTER"/*Eksiltme */
export const INCREASE_BY_TWO_COUNTER="INCREASE_BY_TWO_COUNTER" /*2 arttırma */